apiVersion: autoscaling/v2beta2 
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-resource-metrics-memory 
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: example 
  minReplicas: 1 
  maxReplicas: 3
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: AverageValue 
        averageValue: 2Gi 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: AverageValue 
        averageValue: 800m         
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Max
    scaleUp: 
      policies:
      - type: Percent
        value: 12 
        periodSeconds: 80
      selectPolicy: Max
      stabilizationWindowSeconds: 0
