---
apiVersion: v1
kind: Pod
metadata:
  name: toolkit
  namespace: kong-dev
  labels:
    app: toolkit
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 1000
  containers:
  - name: toolkit
    image: dockerhub/hmsvigle/toolkit-ubuntu:6.0
    command: ['sh','-c','tail -f /dev/null']
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 200Mi
        cpu: 200m
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 1000
      runAsNonRoot: true
  restartPolicy: Never
---
