{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.resource.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.resource.labels | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
  
{{- end }}

