{{- if .Values.networkpolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.resource.name }}-netpol
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.resource.labels | nindent 4 }}
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      {{- toYaml .Values.resource.labels | nindent 6 }}
  policyTypes:
  - Ingress
{{- end }}


