{{- if .Values.type.deployment.enabled }}
{{- if .Values.persistence }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- range .Values.volumeMounts }}
  name: {{ .name | title | lower }}
  {{- end }}
  labels:
    {{- toYaml .Values.resource.labels | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
{{- end }}
