{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.resource.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.resource.labels | nindent 4 }}
type: Opaque
data: 
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end -}}
  {{- end }}
