apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resource.name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.resource.labels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- toYaml .Values.service.ports | nindent 2 }}
  selector:
    {{- toYaml .Values.resource.labels | nindent 4 }}

