{{- if .Values.type.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.resource.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.resource.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.resource.labels | nindent 6 }}
  serviceName: {{ .Values.resource.name }}-svc
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.resource.labels | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- if .Values.volumes }}
      volumes:
      {{- toYaml .Values.volumes | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Values.resource.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

        {{- if .Values.env }}
        env:
        {{- toYaml .Values.env | nindent 8 }}
        {{- end }}

        {{- if .Values.envFrom }}
        envFrom:
        {{- toYaml .Values.envFrom | nindent 8 }}
        {{- end }}
        ports:
        {{- toYaml .Values.ports | nindent 8 }}
        {{- if .Values.volumeMounts }}
        volumeMounts:
        {{- toYaml .Values.volumeMounts | nindent 8 }}
        {{- end }}
        {{- if .Values.probes.enabled }}
        livenessProbe:
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 45 }}
          periodSeconds: 60
          timeoutSeconds: 15
          {{- if .Values.probes.liveness.httpGet }}
          httpGet:
            {{- toYaml .Values.probes.liveness.httpGet | nindent 12 }}
          {{ else }}
          tcpSocket:
            {{- toYaml .Values.probes.liveness.tcpSocket | nindent 12 }}
          {{- end }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 60 }}
          periodSeconds: 60
          timeoutSeconds: 15
          {{- if .Values.probes.readiness.httpGet }}
          httpGet:
            {{- toYaml .Values.probes.readiness.httpGet | nindent 12 }}
          {{ else }}
          tcpSocket:
          {{- toYaml .Values.probes.readiness.tcpSocket | nindent 12 }}
          {{- end }}
        {{- end }}
        resources:
            {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.persistence }}
  volumeClaimTemplates:
  - metadata:
      {{- range .Values.volumeMounts }}
      name: {{ .name | title | lower }}
      {{- end }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }}
{{- end }}
